[tasks.format-rust]
command = "cargo"
args    = [ "fmt" ]

[tasks.format-toml]
command = "taplo"
args    = [ "fmt" ]

[tasks.format-prettier]
command = "prettier"
args    = [ "--write", "." ]


[tasks.format]
dependencies = [
  "format-rust",
  "format-toml",
  "format-prettier",
]
