[tasks.rustfmt]
command = "cargo"
args    = [ "fmt" ]

[tasks.taplo]
command = "taplo"
args    = [ "fmt" ]

[tasks.prettier]
command = "prettier"
args    = [ "--write", "." ]

[tasks.format]
dependencies = [
  "rustfmt",
  "taplo",
  "prettier",
]
